-- Toko Zaina inventory schema. UUID values are generated by the application.

CREATE TABLE users (
  id UUID PRIMARY KEY,
  username VARCHAR(80) NOT NULL,
  display_name VARCHAR(120) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  password_changed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ck_users_username_not_blank CHECK (LENGTH(TRIM(username)) > 0)
);

CREATE UNIQUE INDEX uk_users_username_lower ON users (LOWER(username));

CREATE TABLE categories (
  id UUID PRIMARY KEY,
  name VARCHAR(80) NOT NULL,
  color CHAR(7) NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ck_categories_color CHECK (color ~ '^#[0-9A-Fa-f]{6}$')
);

CREATE UNIQUE INDEX uk_categories_name_lower ON categories (LOWER(name));

CREATE TABLE products (
  id UUID PRIMARY KEY,
  category_id UUID NOT NULL,
  sku VARCHAR(60) NOT NULL,
  barcode VARCHAR(100),
  name VARCHAR(160) NOT NULL,
  location VARCHAR(100),
  base_unit VARCHAR(40) NOT NULL,
  cost_price BIGINT NOT NULL DEFAULT 0,
  sale_price BIGINT NOT NULL DEFAULT 0,
  minimum_stock NUMERIC(18,3) NOT NULL DEFAULT 0,
  image_url VARCHAR(500),
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_products_category FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE RESTRICT,
  CONSTRAINT ck_products_cost_price CHECK (cost_price >= 0),
  CONSTRAINT ck_products_sale_price CHECK (sale_price >= 0),
  CONSTRAINT ck_products_minimum_stock CHECK (minimum_stock >= 0),
  CONSTRAINT ck_products_name_not_blank CHECK (LENGTH(TRIM(name)) > 0),
  CONSTRAINT ck_products_sku_not_blank CHECK (LENGTH(TRIM(sku)) > 0)
);

CREATE UNIQUE INDEX uk_products_sku_lower ON products (LOWER(sku));
CREATE UNIQUE INDEX uk_products_barcode ON products (barcode) WHERE barcode IS NOT NULL;
CREATE INDEX idx_products_category_active ON products (category_id, is_active);
CREATE INDEX idx_products_name_lower ON products (LOWER(name));

CREATE TABLE product_units (
  id UUID PRIMARY KEY,
  product_id UUID NOT NULL,
  name VARCHAR(40) NOT NULL,
  factor NUMERIC(18,3) NOT NULL,
  sale_price BIGINT NOT NULL,
  is_default BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_product_units_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE RESTRICT,
  CONSTRAINT ck_product_units_factor CHECK (factor > 0),
  CONSTRAINT ck_product_units_sale_price CHECK (sale_price >= 0),
  CONSTRAINT ck_product_units_name_not_blank CHECK (LENGTH(TRIM(name)) > 0)
);

CREATE UNIQUE INDEX uk_product_units_name_lower ON product_units (product_id, LOWER(name));
CREATE UNIQUE INDEX uk_product_units_default ON product_units (product_id) WHERE is_default = TRUE;
CREATE INDEX idx_product_units_product ON product_units (product_id);

CREATE TABLE inventory_balances (
  product_id UUID PRIMARY KEY,
  quantity_base NUMERIC(18,3) NOT NULL DEFAULT 0,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_inventory_balances_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE RESTRICT,
  CONSTRAINT ck_inventory_balances_non_negative CHECK (quantity_base >= 0)
);

CREATE TABLE sales (
  id UUID PRIMARY KEY,
  sale_number VARCHAR(40) NOT NULL UNIQUE,
  idempotency_key UUID NOT NULL UNIQUE,
  sold_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  status VARCHAR(20) NOT NULL DEFAULT 'COMPLETED',
  subtotal BIGINT NOT NULL,
  discount BIGINT NOT NULL DEFAULT 0,
  total BIGINT NOT NULL,
  amount_paid BIGINT NOT NULL,
  change_amount BIGINT NOT NULL,
  note VARCHAR(500),
  created_by UUID NOT NULL,
  cancelled_at TIMESTAMPTZ,
  cancellation_reason VARCHAR(500),
  cancelled_by UUID,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_sales_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE RESTRICT,
  CONSTRAINT fk_sales_cancelled_by FOREIGN KEY (cancelled_by) REFERENCES users(id) ON DELETE RESTRICT,
  CONSTRAINT ck_sales_status CHECK (status IN ('COMPLETED', 'CANCELLED')),
  CONSTRAINT ck_sales_money_non_negative CHECK (subtotal >= 0 AND discount >= 0 AND total >= 0 AND amount_paid >= 0 AND change_amount >= 0),
  CONSTRAINT ck_sales_total CHECK (total = subtotal - discount),
  CONSTRAINT ck_sales_payment CHECK (amount_paid >= total AND change_amount = amount_paid - total),
  CONSTRAINT ck_sales_cancellation CHECK (
    (status = 'COMPLETED' AND cancelled_at IS NULL AND cancellation_reason IS NULL AND cancelled_by IS NULL)
    OR
    (status = 'CANCELLED' AND cancelled_at IS NOT NULL AND cancellation_reason IS NOT NULL AND cancelled_by IS NOT NULL)
  )
);

CREATE INDEX idx_sales_sold_at ON sales (sold_at);
CREATE INDEX idx_sales_status_sold_at ON sales (status, sold_at);

CREATE TABLE sale_items (
  id UUID PRIMARY KEY,
  sale_id UUID NOT NULL,
  product_id UUID NOT NULL,
  unit_id UUID NOT NULL,
  product_name VARCHAR(160) NOT NULL,
  unit_name VARCHAR(40) NOT NULL,
  factor_snapshot NUMERIC(18,3) NOT NULL,
  quantity_input NUMERIC(18,3) NOT NULL,
  quantity_base NUMERIC(18,3) NOT NULL,
  unit_price BIGINT NOT NULL,
  cost_price BIGINT NOT NULL,
  subtotal BIGINT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_sale_items_sale FOREIGN KEY (sale_id) REFERENCES sales(id) ON DELETE RESTRICT,
  CONSTRAINT fk_sale_items_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE RESTRICT,
  CONSTRAINT fk_sale_items_unit FOREIGN KEY (unit_id) REFERENCES product_units(id) ON DELETE RESTRICT,
  CONSTRAINT ck_sale_items_quantity CHECK (factor_snapshot > 0 AND quantity_input > 0 AND quantity_base > 0),
  CONSTRAINT ck_sale_items_money CHECK (unit_price >= 0 AND cost_price >= 0 AND subtotal >= 0)
);

CREATE INDEX idx_sale_items_sale ON sale_items (sale_id);
CREATE INDEX idx_sale_items_product ON sale_items (product_id);

CREATE TABLE stock_movements (
  id UUID PRIMARY KEY,
  idempotency_key UUID NOT NULL UNIQUE,
  product_id UUID NOT NULL,
  unit_id UUID NOT NULL,
  movement_type VARCHAR(30) NOT NULL,
  quantity_input NUMERIC(18,3) NOT NULL,
  factor_snapshot NUMERIC(18,3) NOT NULL,
  quantity_base NUMERIC(18,3) NOT NULL,
  balance_after NUMERIC(18,3) NOT NULL,
  unit_cost BIGINT,
  supplier_name VARCHAR(160),
  reference_id UUID,
  external_reference VARCHAR(100),
  note VARCHAR(500),
  created_by UUID NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_stock_movements_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE RESTRICT,
  CONSTRAINT fk_stock_movements_unit FOREIGN KEY (unit_id) REFERENCES product_units(id) ON DELETE RESTRICT,
  CONSTRAINT fk_stock_movements_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE RESTRICT,
  CONSTRAINT ck_stock_movements_type CHECK (movement_type IN (
    'OPENING', 'RECEIPT', 'SALE', 'SALE_REVERSAL', 'DAMAGE',
    'ADJUSTMENT_IN', 'ADJUSTMENT_OUT', 'RETURN_IN', 'RETURN_OUT'
  )),
  CONSTRAINT ck_stock_movements_quantity CHECK (quantity_input > 0 AND factor_snapshot > 0 AND quantity_base <> 0 AND balance_after >= 0),
  CONSTRAINT ck_stock_movements_unit_cost CHECK (unit_cost IS NULL OR unit_cost >= 0)
);

CREATE INDEX idx_stock_movements_product_created ON stock_movements (product_id, created_at);
CREATE INDEX idx_stock_movements_type_created ON stock_movements (movement_type, created_at);
CREATE INDEX idx_stock_movements_reference ON stock_movements (reference_id) WHERE reference_id IS NOT NULL;

CREATE TABLE store_settings (
  id SMALLINT PRIMARY KEY DEFAULT 1,
  store_name VARCHAR(160) NOT NULL,
  address VARCHAR(500),
  phone VARCHAR(40),
  timezone VARCHAR(80) NOT NULL DEFAULT 'Asia/Jakarta',
  default_minimum_stock NUMERIC(18,3) NOT NULL DEFAULT 5,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ck_store_settings_singleton CHECK (id = 1),
  CONSTRAINT ck_store_settings_default_stock CHECK (default_minimum_stock >= 0)
);

CREATE TABLE session (
  sid VARCHAR NOT NULL PRIMARY KEY,
  sess JSON NOT NULL,
  expire TIMESTAMP(6) NOT NULL
);

CREATE INDEX idx_session_expire ON session (expire);
